//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class project_databaseEntities : DbContext
    {
        public project_databaseEntities()
            : base("name=project_databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<game> games { get; set; }
        public virtual DbSet<in_lobby> in_lobby { get; set; }
        public virtual DbSet<lobby> lobbies { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
