//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        public int ID { get; set; }
        public string name { get; set; }
        public int max_players { get; set; }
        public int game_count { get; set; }
        public int max_playing_time { get; set; }
    }
}
