//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_lobby
    {
        public int pk_id { get; set; }
        public int userid { get; set; }
        public int lobbyid { get; set; }

        public in_lobby()
        {
             
        }

        public in_lobby(int pk_id, int userid, int lobbyid)
        {
            this.userid = userid;
            this.pk_id = pk_id;
            this.lobbyid = lobbyid;
        }
    }
}
