//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class lobby
    {
        public int ID { get; set; }
        public int game_id { get; set; }
        public int nr_of_players { get; set; }
        public int currently_in_lobby { get; set; }
        public System.DateTime start_date { get; set; }
        public string creator_name { get; set; }

        public lobby()
        {

        }
        public lobby(int ID, int game_id, int nr_of_players, DateTime start_date, string creator_name, int currently_in_lobby)
        {
            this.ID = ID;
            this.game_id = game_id;
            this.nr_of_players = nr_of_players;
            this.start_date = start_date;
            this.creator_name = creator_name;
            this.currently_in_lobby = currently_in_lobby;
        }
    }
}
