//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string tel { get; set; }
        public System.DateTime registration_date { get; set; }
        public int created_lobbies { get; set; }
        public int joined_lobbies { get; set; }
        public int canceled_lobbies { get; set; }

        public user()
        {

        } 
        public user(int ID, string name, DateTime registration_date, int created_lobbies, int joined_lobbies, int canceled_lobbies)
        {
            this.ID = ID;
            this.name = name;
            this.registration_date = registration_date;
            this.created_lobbies = created_lobbies;
            this.joined_lobbies = joined_lobbies;
            this.canceled_lobbies = canceled_lobbies;
            this.tel = "0000000000";
        }
    }
}
